# Data Gathering

In [1]:
import pandas as pd
df = pd.read_csv('twitter_training.csv')

# Data Exploration

In [2]:
df

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   2401                                                   74681 non-null  int64
 1   Borderlands                                            74681 non-null  str
 2   Positive                                               74681 non-null  str
 3   im getting on borderlands and i will murder you all ,  73995 non-null  str
dtypes: int64(1), str(3)
memory usage: 11.4 MB

In [4]:
df.isna().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    686
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(2700)

In [6]:
df['Positive'].value_counts()

Positive
Negative      22542
Positive      20831
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

# Data Cleaning

In [7]:
df= df[df['Positive']!='Irrelevant']

In [8]:
df.drop(columns=['2401','Borderlands'],inplace=True)

In [9]:
df.rename(columns={'Positive':'Sentiment','im getting on borderlands and i will murder you all ,':'Tweets'},inplace=True)

In [10]:
df.dropna(inplace=True)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df

      Sentiment                                             Tweets
0      Positive  I am coming to the borders and I will kill you...
1      Positive  im getting on borderlands and i will kill you ...
2      Positive  im coming on borderlands and i will murder you...
3      Positive  im getting on borderlands 2 and i will murder ...
4      Positive  im getting into borderlands and i can murder y...
...         ...                                                ...
74676  Positive  Just realized that the Windows partition of my...
74677  Positive  Just realized that my Mac window partition is ...
74678  Positive  Just realized the windows partition of my Mac ...
74679  Positive  Just realized between the windows partition of...
74680  Positive  Just like the windows partition of my Mac is l...

[57484 rows x 2 columns]

# Feature Encoding

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sentiment'] = le.fit_transform(df['Sentiment'])

In [34]:
print(le.classes_)

['Negative' 'Neutral' 'Positive']

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [15]:
tok = Tokenizer(oov_token='Nothing')
tok.fit_on_texts(df['Tweets'])

In [16]:
vocab_size = len(tok.word_index)+1 #Vocabulary Size

In [17]:
tok.word_counts

OrderedDict([('i', 24307),
             ('am', 1516),
             ('coming', 403),
             ('to', 23272),
             ('the', 35286),
             ('borders', 11),
             ('and', 21550),
             ('will', 2674),
             ('kill', 348),
             ('you', 9290),
             ('all', 4490),
             ('im', 547),
             ('getting', 1046),
             ('on', 9736),
             ('borderlands', 1412),
             ('murder', 67),
             ('2', 3709),
             ('me', 5514),
             ('into', 947),
             ('can', 2891),
             ('so', 6395),
             ('spent', 179),
             ('a', 19027),
             ('few', 467),
             ('hours', 481),
             ('making', 527),
             ('something', 752),
             ('for', 12481),
             ('fun', 1329),
             ('if', 2855),
             ("don't", 1337),
             ('know', 1391),
             ('huge', 310),
             ('fan', 228),
             ('maya', 22),
             ('is', 14272),
             ('one', 2917),
             ('of', 15261),
             ('my', 9731),
             ('favorite', 517),
             ('characters', 192),
             ('decided', 194),
             ('make', 1399),
             ('myself', 313),
             ('wallpaper', 14),
             ('pc', 624),
             ('here', 1236),
             ('original', 188),
             ('image', 54),
             ('versus', 13),
             ('creation', 6),
             ('made', 847),
             ('enjoy', 376),
             ('pic', 3316),
             ('twitter', 3167),
             ('com', 7744),
             ('mlsi5wf9jg', 4),
             ('couple', 132),
             ('doing', 561),
             ('that', 7976),
             ("i'm", 2532),
             ("here's", 108),
             ('picture', 83),
             ('compared', 63),
             ('have', 5087),
             ('rhandlerr', 1718),
             ('2010', 60),
             ('was', 4364),
             ('rock', 69),
             ('hard', 472),
             ('la', 71),
             ('varlope', 4),
             ('rare', 33),
             ('powerful', 147),
             ('handsome', 69),
             ('jackpot', 9),
             ('3', 2470),
             ('xbox', 1778),
             ('dlvr', 291),
             ('it', 11782),
             ('rmtrgf', 6),
             ('dfr', 7),
             ('vita', 12),
             ('but', 5203),
             ('1', 1832),
             ('live', 832),
             ('music', 274),
             ('sega', 26),
             ('from', 3549),
             ('e', 376),
             ('like', 3846),
             ('london', 21),
             ('de', 99),
             ('2011', 45),
             ('first', 1270),
             ('session', 73),
             ('in', 12699),
             ('long', 594),
             ('time', 2240),
             ('where', 640),
             ('actually', 900),
             ('had', 1608),
             ('really', 2681),
             ('satisfying', 48),
             ('combat', 59),
             ('experience', 294),
             ('got', 1838),
             ('some', 2187),
             ('good', 2816),
             ('kills', 199),
             ('this', 11742),
             ('fighting', 59),
             ('enjoyed', 159),
             ('rather', 123),
             ('real', 539),
             ('nice', 715),
             ('wait', 1145),
             ('hot', 196),
             ('row', 136),
             ('bad', 1237),
             ('did', 903),
             ('biggest', 179),
             ('dissappoinment', 4),
             ('life', 605),
             ('came', 273),
             ('out', 3560),
             ('year', 1090),
             ('ago', 301),
             ('fuck', 1692),
             ('disappointment', 62),
             ('male', 17),
             ('hanging', 62),
             ('back', 1613),
             ('last', 1010),
             ('we', 3033),
             ('finished', 296),
             ('finally', 798),
             ('yas', 10),
             ('thank', 1133),
             ('everyone', 822),
             ('try', 492),
             ('stream', 644),
             ('tomorrow', 300),
             ('not', 4638),
             ('might', 302),
             ('irl', 44),
             ('streams', 57),
             ('while', 663),
             ('awayu', 4),
             ('shall', 40),
             ('see', 1794),
             ('much', 1547),
             ('raids', 29),
             ('mompou', 6),
             ('mumpow', 6),
             ('megamagwitch', 4),
             ('kfdmitch', 3),
             ('find', 439),
             ('yes', 271),
             ("i'll", 310),
             ('maybe', 404),
             ("we'll", 56),
             ('thanks', 1032),
             ('up', 2552),
             ('get', 3406),
             ('haircut', 8),
             ("wasn't", 82),
             ('would', 1340),
             ('still', 2121),
             ('be', 5657),
             ('hawaii', 3),
             ('megamagwife', 1),
             ('fendmitch', 1),
             ('update', 775),
             ('guys', 968),
             ('even', 1771),
             ('go', 1701),
             ('hope', 464),
             ('10', 1087),
             ('never', 1138),
             ('both', 554),
             ('or', 2439),
             ('4', 1302),
             ('hey', 554),
             ('use', 563),
             ('how', 2393),
             ('many', 762),
             ('their', 1481),
             ('man', 886),
             ('gearbox', 30),
             ('needs', 292),
             ('fix', 1447),
             ('dissapointing', 3),
             ('drops', 94),
             ('new', 2849),
             ('dlc', 156),
             ('cant', 414),
             ('fine', 132),
             ('farm', 24),
             ('bosses', 15),
             ('mayhem', 64),
             ('legendary', 124),
             ('drop', 172),
             ('anywhere', 103),
             ('else', 285),
             ('6', 670),
             ('sucks', 290),
             ('alot', 31),
             ('these', 1304),
             ('disappointing', 82),
             ('elsewhere', 13),
             ('disssapointing', 1),
             ('bethesda', 32),
             ('completely', 271),
             ('days', 660),
             ('having', 657),
             ('foot', 38),
             ('unk', 2356),
             ('force', 95),
             ('check', 582),
             ('epic', 360),
             ('streamer', 44),
             ('watch', 995),
             ('striptease', 2),
             ('our', 1368),
             ('big', 781),
             ('blaming', 8),
             ('sight', 22),
             ('tardiness', 2),
             ('little', 502),
             ('bit', 644),
             ('called', 231),
             ('early', 220),
             ('work', 1043),
             ("can't", 1422),
             ('sorry', 295),
             ('loves', 47),
             ('twitch', 1067),
             ('tv', 1335),
             ('punnisenpai', 3),
             ('borderland', 12),
             ('morning', 289),
             ('catch', 52),
             ('love', 2481),
             ('guilty', 34),
             ('sobriety', 1),
             ('borderline', 5),
             ('why', 2395),
             ('does', 610),
             ('every', 1152),
             ('slicked', 4),
             ('hair', 105),
             ('haven’t', 93),
             ('heard', 144),
             ('bangs', 5),
             ('stupid', 461),
             ('assholes', 43),
             ('border', 39),
             ('countries', 22),
             ('your', 3524),
             ('fallen', 27),
             ('off', 1043),
             ('are', 4647),
             ('aliens', 22),
             ('beth', 9),
             ('she', 274),
             ('haven', 42),
             ('’', 2020),
             ('t', 3070),
             ('enough', 381),
             ('gray', 11),
             ('practically', 16),
             ('france', 4),
             ('greedy', 43),
             ('45', 41),
             ('what', 2502),
             ('going', 1538),
             ('finish', 137),
             ('today', 1241),
             ("i've", 1039),
             ('commands', 25),
             ('set', 229),
             ('looking', 605),
             ('forward', 316),
             ('starting', 224),
             ('about', 2799),
             ('hour', 254),
             ('start', 513),
             ('an', 2707),
             ('installed', 75),
             ('events', 86),
             ('look', 782),
             ('20', 686),
             ('cleaning', 9),
             ('just', 5423),
             ('her', 595),
             ('volume', 20),
             ('awesome', 642),
             ('server', 296),
             ('imma', 55),
             ('probably', 480),
             ('play', 3029),
             ('tps', 11),
             ("that'll", 14),
             ('playing', 1864),
             ("it's", 2186),
             ("that'yer", 1),
             ('ll', 88),
             ('video', 1055),
             ('own', 408),
             ('profzeroo', 5),
             ('w', 371),
             ('3‼', 2),
             ('him', 565),
             ('buff', 138),
             ('ly', 627),
             ('2wmmip5', 6),
             ('say', 816),
             ('shouts', 19),
             ('chat', 113),
             ('chance', 437),
             ('shout', 86),
             ('upcoming', 62),
             ('profzero', 1),
             ('p', 336),
             ('–', 190),
             ('also', 1258),
             ('shows', 166),
             ('via', 797),
             ('at', 4178),
             ('officially', 79),
             ('series', 1088),
             ('its', 1456),
             ('movies', 35),
             ('invitation', 8),
             ('invites', 2),
             ('yessssssss', 4),
             ('fick', 5),
             ('yessssss', 2),
             ('hate', 676),
             ('easy', 216),
             ('modifier', 11),
             ('event', 272),
             ('won’t', 112),
             ('forever', 143),
             ('most', 972),
             ('i’ve', 313),
             ('game', 7337),
             ('since', 795),
             ('they', 2924),
             ('added', 113),
             ('them', 1319),
             ('horrible', 91),
             ('modifiers', 22),
             ('please', 1669),
             ('give', 655),
             ('option', 129),
             ('turn', 204),
             ('pls', 171),
             ('simple', 119),
             ('chaos', 40),
             ("won't", 344),
             ("that's", 480),
             ('terrible', 294),
             ('saying', 277),
             ('day', 1318),
             ('9', 331),
             ('ability', 43),
             ('thinking', 187),
             ('total', 109),
             ('won', 488),
             ('absolutely', 393),
             ('ridiculous', 181),
             ('ve', 189),
             ('almost', 477),
             ('do', 2472),
             ('best', 1918),
             ('taken', 108),
             ('past', 217),
             ('until', 501),
             ('send', 100),
             ('grounded', 5),
             ('looked', 110),
             ('pretty', 575),
             ('cool', 565),
             ('despite', 88),
             ('tier', 64),
             ('unfunny', 6),
             ('writing', 68),
             ('became', 78),
             ('yet', 470),
             ('another', 883),
             ('survival', 19),
             ('crafting', 5),
             ('can’t', 465),
             ('shitty', 138),
             ('trend', 37),
             ('die', 262),
             ('crappy', 43),
             ('grosskreutz', 1),
             ('spelling', 12),
             ('turned', 115),
             ('crap', 180),
             ('mod', 18),
             ('deep', 72),
             ('fifth', 16),
             ('format', 23),
             ('ultimately', 7),
             ('mobile', 529),
             ('top', 554),
             ('annoying', 245),
             ('seriously', 254),
             ('submit', 29),
             ('complaint', 29),
             ('ceo', 35),
             ("isn't", 145),
             ('paying', 95),
             ('his', 731),
             ('staff', 77),
             ('bonuses', 20),
             ('file', 79),
             ("doesn't", 446),
             ('pay', 438),
             ('employees', 128),
             ('competitors', 16),
             ('suppose', 23),
             ("isn'ain", 1),
             ('entire', 232),
             ('now', 3489),
             ('any', 988),
             ('offering', 27),
             ('fuckin', 100),
             ('trash', 387),
             ('damn', 893),
             ('rubbish', 19),
             ('fucking', 1661),
             ('thrash', 40),
             ('shit', 2215),
             ('35', 58),
             ('played', 1016),
             ('through', 574),
             ('actual', 127),
             ('great', 1768),
             ('guns', 54),
             ('feel', 565),
             ('once', 270),
             ('felt', 141),
             ('needed', 112),
             ('grind', 70),
             ('story', 476),
             ('other', 718),
             ('hand', 118),
             ('very', 1287),
             ('eventual', 5),
             ('cutscene', 15),
             ('skip', 18),
             ('by', 2336),
             ('weapons', 85),
             ('funny', 215),
             ('sequence', 7),
             ('occasional', 2),
             ('slip', 7),
             ('open', 411),
             ('someone', 581),
             ('side', 162),
             ('endless', 29),
             ('5', 1571),
             ('were', 729),
             ('sure', 446),
             ('oh', 568),
             ("yes'm", 1),
             ('extended', 21),
             ('come', 712),
             ('meet', 92),
             ('lovely', 73),
             ('gaming', 481),
             ('goddesses', 5),
             ('gambling', 23),
             ('beautiful', 395),
             ('gods', 33),
             ('16', 128),
             ('green', 67),
             ('bitch', 169),
             ('slut', 10),
             ('miracle', 27),
             ('ok', 266),
             ('loving', 146),
             ('bombs', 18),
             ('over', 1396),
             ('baghdad', 4),
             ('anything', 424),
             ('gets', 367),
             ('hype', 85),
             ('concept', 59),
             ('a1', 9),
             ('gives', 120),
             ('baghad', 1),
             ('seeing', 225),
             ('take', 667),
             ('sir', 64),
             ('case', 117),
             ('earth', 51),
             ('rpg', 40),
             ('uninstalled', 42),
             ('games', 1946),
             ('space', 85),
             ('uninstall', 17),
             ('room', 118),
             ('deleted', 114),
             ('watching', 335),
             ('already', 749),
             ('bleeding', 17),
             ('edge', 133),
             ('clever', 15),
             ('cross', 96),
             ('between', 185),
             ('overwatch', 891),
             ('domination', 9),
             ('mode', 398),
             ('as', 3098),
             ('crossroads', 1),
             ('future', 157),
             ('2016', 95),
             ('fantasy', 111),
             ('non', 78),
             ('bioshock', 25),
             ('switch', 230),
             ('count', 53),
             ('desert', 13),
             ('montana', 1),
             ('after', 1521),
             ('platinum', 48),
             ('loot', 112),
             ('booty', 15),
             ('lot', 567),
             ('has', 2574),
             ('named', 39),
             ('reason', 345),
             ('laptop', 100),
             ('run', 355),
             ('war', 655),
             ('thunder', 23),
             ('warframe', 5),
             ('high', 310),
             ('settings', 75),
             ('moment', 179),
             ('launch', 321),
             ('csgo', 765),
             ('computer', 151),
             ('crashes', 130),
             ('whole', 451),
             ('breaks', 32),
             ('down', 933),
             ('firefox', 36),
             ('plus', 162),
             ('no', 2801),
             ('easily', 72),
             ('currently', 171),
             ('dare', 23),
             ('mind', 192),
             ('software', 127),
             ('mount', 49),
             ('act', 72),
             ('king', 100),
             ('speeds', 50),
             ('jumping', 51),
             ('more', 2550),
             ('dlcs', 13),
             ('vibing', 3),
             ('playlists', 15),
             ('vibe', 28),
             ('dropping', 73),
             ('quality', 145),
             ('720p', 4),
             ('makes', 521),
             ('difference', 57),
             ('well', 972),
             ('runs', 105),
             ('dumb', 131),
             ('internet', 433),
             ('lmao', 222),
             ('heyitscece', 3),
             ('streaming', 271),
             ('vibrating', 1),
             ('lowering', 5),
             ('jon', 20),
             ('downloading', 49),
             ('tumb', 2),
             ('enter', 99),
             ('gunner', 12),
             ('seat', 20),
             ('fear', 68),
             ('step', 68),
             ('trench', 1),
             ('then', 1160),
             ('wav1bacr5j', 4),
             ('wikipedia', 216),
             ('org', 382),
             ('v', 1007),
             ('omg', 219),
             ('ever', 1230),
             ('thwarted', 4),
             ('bank', 78),
             ('foiled', 1),
             ('threatened', 14),
             ('who', 1540),
             ('late', 182),
             ('trip', 43),
             ('seems', 315),
             ('broken', 376),
             ('with', 7190),
             ('m10', 6),
             ('rates', 18),
             ('constantly', 83),
             ('less', 236),
             ('than', 1331),
             ('lower', 87),
             ('levels', 43),
             ('possible', 138),
             ('2500', 9),
             ('swear', 96),
             ('greens', 5),
             ('blues', 23),
             ('boss', 75),
             ('falling', 53),
             ('when', 2617),
             ('rate', 83),
             ('production', 57),
             ('kinda', 225),
             ('pushing', 37),
             ('normal', 85),
             ('people', 1971),
             ('moving', 75),
             ('recovery', 41),
             ('fast', 173),
             ('next', 851),
             ('gold', 251),
             ('amounts', 12),
             ('worked', 158),
             ('polycule', 4),
             ('tonight', 384),
             ('magical', 23),
             ('evening', 61),
             ('end', 413),
             ('sigh', 27),
             ('allowed', 45),
             ('polyphony', 1),
             ('polyslice', 1),
             ('better', 758),
             ('part', 410),
             ('same', 609),
             ('jackson', 50),
             ('happy', 909),
             ('profit', 40),
             ('wise', 27),
             ('expected', 68),
             ('due', 324),
             ('budget', 32),
             ('realize', 74),
             ('because', 1753),
             ('busted', 29),
             ('again', 1352),
             ('only', 1567),
             ('marketing', 87),
             ('business', 396),
             ('prior', 3),
             ('problem', 507),
             ('far', 422),
             ('always', 807),
             ('fav', 49),
             ('certainly', 97),
             ('guardian', 24),
             ('around', 444),
             ('weekend', 260),
             ('managed', 75),
             ('done', 621),
             ('enjoying', 136),
             ('loved', 216),
             ('slutty', 5),
             ('mechanic', 29),
             ('slutsky', 1),
             ('old', 579),
             ('night', 532),
             ('heeps', 4),
             ("we're", 190),
             ('closer', 31),
             ('towards', 102),
             ('raided', 16),

In [18]:
sequences = tok.texts_to_sequences(df['Tweets'])

In [19]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='pre') #maxlen=1000 is also a parameter

In [20]:
sequences

array([[   0,    0,    0, ...,  452,   15,   28],
       [   0,    0,    0, ...,  452,   15,   28],
       [   0,    0,    0, ..., 1732,   15,   28],
       ...,
       [   0,    0,    0, ...,  152, 1020, 2536],
       [   0,    0,    0, ...,   78,   41, 2536],
       [   0,    0,    0, ...,    3, 1020, 2536]],
      shape=(57484, 166), dtype=int32)

In [21]:
from tensorflow.keras.layers import SimpleRNN,Input,Dense,Embedding,Dropout
from tensorflow.keras.models import Sequential

In [22]:
X = sequences

In [23]:
Y = df['Sentiment'].values

In [24]:
Y

array([2, 2, 2, ..., 2, 2, 2], shape=(57484,))

In [25]:
X

array([[   0,    0,    0, ...,  452,   15,   28],
       [   0,    0,    0, ...,  452,   15,   28],
       [   0,    0,    0, ..., 1732,   15,   28],
       ...,
       [   0,    0,    0, ...,  152, 1020, 2536],
       [   0,    0,    0, ...,   78,   41, 2536],
       [   0,    0,    0, ...,    3, 1020, 2536]],
      shape=(57484, 166), dtype=int32)

In [26]:
vocab_size

29230

In [27]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [28]:
model = Sequential([Input(shape=(99,)),
                    Embedding(input_dim=vocab_size,output_dim=128,mask_zero=True),
                    SimpleRNN(32),
                    Dropout(0.3),
                    Dense(3,activation='softmax')
                    ])

In [29]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [30]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 99, 128)        │     3,741,440 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         5,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,746,691 (14.29 MB)

 Trainable params: 3,746,691 (14.29 MB)

 Non-trainable params: 0 (0.00 B)

In [31]:
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10,callbacks=[early_stop],batch_size=64)

Epoch 1/10
719/719 ━━━━━━━━━━━━━━━━━━━━ 30s 39ms/step - accuracy: 0.7494 - loss: 0.6068 - val_accuracy: 0.8819 - val_loss: 0.3225
Epoch 2/10
719/719 ━━━━━━━━━━━━━━━━━━━━ 30s 42ms/step - accuracy: 0.9355 - loss: 0.1848 - val_accuracy: 0.9022 - val_loss: 0.2683
Epoch 3/10
719/719 ━━━━━━━━━━━━━━━━━━━━ 31s 43ms/step - accuracy: 0.9674 - loss: 0.0918 - val_accuracy: 0.9143 - val_loss: 0.2641
Epoch 4/10
719/719 ━━━━━━━━━━━━━━━━━━━━ 31s 43ms/step - accuracy: 0.9768 - loss: 0.0653 - val_accuracy: 0.9138 - val_loss: 0.2814
Epoch 5/10
719/719 ━━━━━━━━━━━━━━━━━━━━ 30s 42ms/step - accuracy: 0.9811 - loss: 0.0522 - val_accuracy: 0.9111 - val_loss: 0.3055
Epoch 6/10
719/719 ━━━━━━━━━━━━━━━━━━━━ 31s 42ms/step - accuracy: 0.9843 - loss: 0.0442 - val_accuracy: 0.9095 - val_loss: 0.3329

In [32]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tok,file)

In [33]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.